name: cyberlab_auth_http

services:
  auth-lab:
    build:
      context: ../common/edu_lab
      dockerfile: Dockerfile
    container_name: cyberlab_auth_http_lab
    environment:
      SCENARIO_ID: S02
      LAB_MODE: auth_http
      APP_TITLE: CyberLab - Autenticación Web Vulnerable
    ports:
      - "127.0.0.1:${AUTH_HTTP_PORT:-8082}:5000"
    networks:
      - auth_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

  auth-attacker:
    build:
      context: ../common/attacker
      dockerfile: Dockerfile
    container_name: cyberlab_auth_http_attacker
    environment:
      TARGET_HOST: auth-lab
    volumes:
      - ../common/wordlists:/wordlists:ro
    networks:
      - auth_net
    depends_on:
      - auth-lab
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

networks:
  auth_net:
    driver: bridge