name: cyberlab_auth_http

services:
  auth-lab:
    build:
      context: ./app
      dockerfile: Dockerfile
    container_name: cyberlab_auth_lab
    environment:
      SCENARIO_ID: S02
      LAB_MODE: auth
      APP_TITLE: CyberLab - Autenticación HTTP
    ports:
      - "127.0.0.1:${AUTH_PORT:-8081}:5000"
    networks:
      - auth_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

  auth-attacker:
    image: alpine:3.21
    container_name: auth-attacker
    command: sh -c "apk add --no-cache nmap curl hydra >/dev/null 2>&1; sleep infinity"
    volumes:
      - ../common/wordlists:/wordlists:ro
    networks:
      - auth_net
    init: true

networks:
  auth_net:
    driver: bridge