name: cyberlab_recon

services:
  recon-lab:
    build:
      context: ../common/edu_lab
      dockerfile: Dockerfile
    container_name: cyberlab_recon_lab
    environment:
      SCENARIO_ID: S01
      LAB_MODE: recon
      APP_TITLE: CyberLab - Reconocimiento Nmap/HTTP
    ports:
      - "127.0.0.1:${RECON_PORT:-8081}:5000"
    networks:
      - recon_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

  recon-attacker:
    build:
      context: ../common/attacker
      dockerfile: Dockerfile
    container_name: cyberlab_recon_attacker
    environment:
      TARGET_HOST: recon-lab
    networks:
      - recon_net
    depends_on:
      - recon-lab
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

networks:
  recon_net:
    driver: bridge