name: cyberlab_mitm_lab

services:
  mitm-lab:
    build:
      context: ../common/edu_lab
      dockerfile: Dockerfile
    container_name: cyberlab_mitm_lab
    environment:
      SCENARIO_ID: S05
      LAB_MODE: mitm
      APP_TITLE: CyberLab - MITM simulado en tráfico no cifrado
    ports:
      - "127.0.0.1:${MITM_PORT:-8086}:5000"
    networks:
      - mitm_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

  mitm-attacker:
    build:
      context: ../common/attacker
      dockerfile: Dockerfile
    container_name: cyberlab_mitm_attacker
    cap_add:
      - NET_ADMIN
      - NET_RAW
    environment:
      TARGET_HOST: mitm-lab
    networks:
      - mitm_net
    depends_on:
      - mitm-lab
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

networks:
  mitm_net:
    driver: bridge