name: cyberlab_auth_services

services:
  auth-services-lab:
    build:
      context: ../common/edu_lab
      dockerfile: Dockerfile
    container_name: cyberlab_auth_services_lab
    environment:
      SCENARIO_ID: S04
      LAB_MODE: auth_services
      APP_TITLE: CyberLab - Autenticación SSH/FTP simulada
      DEMO_USER: estudiante
      DEMO_PASSWORD: laboratorio123
    ports:
      - "127.0.0.1:${AUTH_SERVICES_PORT:-8085}:5000"
    networks:
      - auth_services_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

  auth_services-attacker:
    build:
      context: ../common/attacker
      dockerfile: Dockerfile
    container_name: cyberlab_auth_services_attacker
    environment:
      TARGET_HOST: auth-services-lab
    volumes:
      - ../common/wordlists:/wordlists:ro
    networks:
      - auth_services_net
    depends_on:
      - auth-services-lab
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 256M
    restart: unless-stopped

networks:
  auth_services_net:
    driver: bridge